-- MySQL Script generated by MySQL Workbench
-- 10/12/14 01:13:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `codusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `codrol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `usuario_codusuario` INT NOT NULL,
  PRIMARY KEY (`codrol`, `usuario_codusuario`),
  INDEX `fk_rol_usuario1_idx` (`usuario_codusuario` ASC),
  CONSTRAINT `fk_rol_usuario1`
    FOREIGN KEY (`usuario_codusuario`)
    REFERENCES `mydb`.`usuario` (`codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario_codusuario` INT NOT NULL,
  PRIMARY KEY (`codcliente`, `usuario_codusuario`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_codusuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_codusuario`)
    REFERENCES `mydb`.`usuario` (`codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mascota` (
  `codmascota` INT NOT NULL,
  `numero_ficha` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `raza` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `peso` DECIMAL(10) NOT NULL,
  `mascotacol` VARCHAR(45) NOT NULL,
  `usuario_codusuario` INT NOT NULL,
  `cliente_codcliente` INT NOT NULL,
  PRIMARY KEY (`codmascota`, `usuario_codusuario`, `cliente_codcliente`),
  INDEX `fk_mascota_usuario1_idx` (`usuario_codusuario` ASC),
  INDEX `fk_mascota_cliente1_idx` (`cliente_codcliente` ASC),
  CONSTRAINT `fk_mascota_usuario1`
    FOREIGN KEY (`usuario_codusuario`)
    REFERENCES `mydb`.`usuario` (`codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_cliente1`
    FOREIGN KEY (`cliente_codcliente`)
    REFERENCES `mydb`.`cliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cita` (
  `codcita` INT NOT NULL AUTO_INCREMENT,
  `tipo` DATE NOT NULL,
  `motivo` VARCHAR(100) NOT NULL,
  `fecha` VARCHAR(100) NOT NULL,
  `cliente_codcliente` INT NOT NULL,
  `cliente_usuario_codusuario` INT NOT NULL,
  `mascota_codmascota` INT NOT NULL,
  `mascota_usuario_codusuario` INT NOT NULL,
  `mascota_cliente_codcliente` INT NOT NULL,
  `usuario_codusuario` INT NOT NULL,
  PRIMARY KEY (`codcita`, `cliente_codcliente`, `cliente_usuario_codusuario`, `mascota_codmascota`, `mascota_usuario_codusuario`, `mascota_cliente_codcliente`, `usuario_codusuario`),
  INDEX `fk_cita_cliente1_idx` (`cliente_codcliente` ASC, `cliente_usuario_codusuario` ASC),
  INDEX `fk_cita_mascota1_idx` (`mascota_codmascota` ASC, `mascota_usuario_codusuario` ASC, `mascota_cliente_codcliente` ASC),
  INDEX `fk_cita_usuario1_idx` (`usuario_codusuario` ASC),
  CONSTRAINT `fk_cita_cliente1`
    FOREIGN KEY (`cliente_codcliente` , `cliente_usuario_codusuario`)
    REFERENCES `mydb`.`cliente` (`codcliente` , `usuario_codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_mascota1`
    FOREIGN KEY (`mascota_codmascota` , `mascota_usuario_codusuario` , `mascota_cliente_codcliente`)
    REFERENCES `mydb`.`mascota` (`codmascota` , `usuario_codusuario` , `cliente_codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_usuario1`
    FOREIGN KEY (`usuario_codusuario`)
    REFERENCES `mydb`.`usuario` (`codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
